### ISSUE TITLE
Problems with build Android apk

### ISSUE THREAD

**Issue by xiaoxiaogaobo** [SharpAI/mobile_app_server#13]
=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin https://github.com/PluginCordova/cordova-plugin-zeroconf.git#da07b4f995808e850a67ab1a8ac3d298f330df1b to Cordova project:
   SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
   at exports.runInThisContext (vm.js:53:16)
   at Module._compile (module.js:373:25)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load

**Comment by Sunny-wong** [comment]
fix. The plugin cordova-plugin-zeroconf is updated. @xiaoxiaogaobo
