### ISSUE TITLE
No route on the client or the server for url: "http://localhost:12416/."

### ISSUE THREAD

**Issue by therealmichaelberna** [SharpAI/mobile_app_server#6]
Greetings. I've tried the app 3.0.1
from https://github.com/SharpAI/SharpAIMobileApp/releases/download/3.0.1/sharpai-app.apk
and have been getting the error when launching the app as soon as it opens.

No route on the client or the server for url: "http://localhost:12416/."

I tried it on two android devices (both are v8.1.0) which are connected to WiFi and got the same result on both.
Any suggestions?

**Comment by solderzzc** [comment]
@mykiscool it's so nice to have you test it. The same thing happen on my Huawei P30. Let me figure out the root cause then get back to you the detail.

**Comment by solderzzc** [comment]
@mykiscool I just setup the travis to build debug version, it works on my Android 10(Huawei Pro 30), do you have chance to download it and have a test? URL is:
https://github.com/SharpAI/SharpAIMobileApp/releases/download/3.0.1.3/debug.apk

**Comment by therealmichaelberna** [comment]
Yes, that version solves the issue. I am able to launch the app now. I will go ahead and try to use it. Thanks.
